spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-dancer
    username: chat-dancer
    password: chat-dancer
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  kafka:
    bootstrap-servers: 127.0.0.1:9092
server:
  error:
    include-stacktrace: never

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - prometheus

